In [2]:
%matplotlib inline
import numpy as np
import pandas as pd


np.random.seed(29)



In [4]:
#How likely is it that you roll doubles when rolling two dice?
### set number of trials

n_trials = 10_000
n_rows = 10_000

##roll 2 dice

n_dice = 2
n_col = 2

#use np random choice
# to select from [1,2,3,4,5,6]

rolls = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(n_rows, n_col)

rolls

array([[6, 3],
       [4, 5],
       [3, 5],
       ...,
       [2, 2],
       [1, 5],
       [3, 1]])

In [ ]:
#probability of doubles when rolling two dice
(n_rows = n_col)

In [5]:
## set a list of dice outcomes
outcomes = [1,2,3,4,5,6]

In [6]:
rolls = np.random.choice(outcomes, size = (10_000, 2))

In [7]:
rolls

array([[5, 5],
       [1, 5],
       [4, 3],
       ...,
       [1, 4],
       [2, 6],
       [4, 6]])

In [8]:
rolls_df = pd.DataFrame(rolls)

In [9]:
rolls_df[0] == rolls_df[1]

0  1
0     5  5
1     1  5
2     4  3
3     4  4
4     5  1
...  .. ..
9995  4  1
9996  2  5
9997  1  4
9998  2  6
9999  4  6

[10000 rows x 2 columns]

In [10]:
(rolls_df[0] == rolls_df[1]).mean()

0.1638

In [12]:
## If you flip 8 coins, what is the probability of getting exactly 3 heads? 
trials = 10000
number_coins = 8

coins = np.random.choice(['H','T'], trials * number_coins).reshape(trials,number_coins)

In [13]:
coins_df = pd.DataFrame(coins)

In [ ]:
# What is the probability of getting more than 3 heads?

In [14]:
# set probability

p_webdev = 0.75
p_ds = 0.25

In [15]:
#set the number of bilboards
n_cols = 2
n_trials = 10000

In [ ]:
cohorts = np.random.choice(['wd', 'wd','wd','ds'])

In [16]:
billboard_options = ['DS','WD']

In [17]:
billboards = np.random.choice(billboard_options, size= (n_trials,n_cols), p =[0.75,0.25])

In [18]:
billboards

array([['DS', 'DS'],
       ['DS', 'DS'],
       ['DS', 'DS'],
       ...,
       ['DS', 'DS'],
       ['DS', 'WD'],
       ['DS', 'DS']], dtype='<U2')

In [19]:
billboards == 'DS'

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       ...,
       [ True,  True],
       [ True, False],
       [ True,  True]])

In [21]:
#sum to find the instances of 'DS'
successes = ((billboards == 'DS').sum(axis=1) == 2)

In [22]:
successes.mean()

0.5617

#
### Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [ ]:
### normal distribution of poptart purchases

In [26]:
mean = 3
sd = 1.5
n_days = 5
n_trials = 10000

In [27]:
poptart_sales = np.random.normal(mean,sd,size= (n_trials,n_days))

In [28]:
poptart_sales

array([[5.14281785, 3.14243984, 1.58130182, 3.86650639, 3.51802513],
       [1.34093837, 0.68456971, 5.33573723, 2.79008837, 6.55939687],
       [0.83754989, 2.03904919, 2.85965094, 3.96363   , 2.83551944],
       ...,
       [0.90220289, 5.0027549 , 2.93549825, 1.05657189, 2.59670168],
       [1.43150348, 1.67828036, 3.20728276, 3.66062338, 3.40183932],
       [4.28559329, 2.34446247, 4.45290265, 4.68908304, 2.76286268]])

In [31]:
poptart_sales[poptart_sales < 0] = 0

In [32]:
poptart_weekly_sales = poptart_sales.sum(axis=1)

In [33]:
poptart_weekly_sales

array([17.25109103, 16.71073054, 12.53539946, ..., 12.4937296 ,
       13.37952931, 18.53490413])

In [34]:
(poptart_weekly_sales >= 17).mean()

0.276

In [35]:
### comparison of heights
men = 178
mstd = 8
women = 170
wstd = 6

In [37]:
#1 random height for 1 women
np.random.normal(170,6)

161.72445472488266

In [38]:
### random height for man
np.random.normal(178,8)

186.50086507795433

In [39]:
women_heights = np.random.normal(170,6,10000)

In [40]:
men_heights = np.random.normal(178,8,10000)

In [41]:
(women_heights > men_heights).mean()

0.2089

In [48]:
outcomes = ['S','F']

n_students = 100

In [51]:
downloads = np.random.choice(outcomes, size = (10000,150), p = [249/250,1/250])

In [52]:
((downloads == 'S').sum(axis =1) == 50).mean() 

0.0

In [53]:
((downloads == 'S').sum(axis =1) == 100).mean() 

0.0

In [54]:
bools = downloads == 'S'

In [56]:
number_sux_installs = bools.sum(axis = 1)

In [60]:
((bools.sum(axis = 1))<150).mean()

0.451

In [59]:
(number_sux_installs != 150).mean()

0.451

In [63]:
outcomes = ['S','F']

n_students = 100

downloads = np.random.choice(outcomes, size = (10000,450), p = [249/250,1/250])


((downloads == 'S').sum(axis =1) == 100).mean() 

bools = downloads == 'S'

number_sux_installs = bools.sum(axis = 1)



((bools.sum(axis = 1))<450).mean()


0.8391

In [62]:
(number_sux_installs != 450).mean()

0.8336

In [64]:
## assign some outcomes

#0 = no truck
#1 = truck

trucks = np.random.choice([0,1],size = (10000,3), p =[0.3, 0.7])

In [65]:
trucks

array([[1, 1, 0],
       [1, 0, 1],
       [0, 1, 1],
       ...,
       [0, 0, 1],
       [1, 1, 1],
       [0, 1, 1]])

In [66]:
#probability that no truck shows up
(trucks.sum(axis=1) == 0).mean()

0.0313

In [67]:
#p that the truck shows up at least 1
(trucks.sum(axis=1) >= 1).mean()

0.9687

In [91]:
### p that the truck shows up at least once in a week
week_trucks = np.random.choice([0,1], size = (10000,7), p=[0.3,0.7])

In [92]:
(week_trucks.sum(axis=1) > 0).mean()

0.9998

In [95]:
### 
birthdates = range(0,366)

n_students = 23

In [98]:
birthday = np.random.choice(birthdates, size = (10000,23))

In [99]:
birthday

array([[352, 146, 148, ...,  49,  83, 301],
       [256,  76, 175, ..., 111, 314, 235],
       [330, 259, 261, ...,  16, 296, 319],
       ...,
       [259,  59,   3, ...,  39,  40,  57],
       [317, 139,  17, ..., 292, 348,  92],
       [244, 289, 101, ..., 312, 168,  79]])

In [100]:
birthday_df = pd.DataFrame(birthday)

In [104]:
#check that the unique value count corresponds to at least 2 sharing a birhtday
(birthday_df.nunique(axis = 1) != 23)

0        True
1       False
2       False
3        True
4       False
        ...  
9995    False
9996     True
9997     True
9998     True
9999    False
Length: 10000, dtype: bool

In [105]:
(birthday_df.nunique(axis = 1) != 23).mean()

0.501

In [107]:
#looking for 40 students now
birthday = np.random.choice(birthdates, size = (10000,40))
birthday_df = pd.DataFrame(birthday)
(birthday_df.nunique(axis = 1) != 40).mean()

0.8894