In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz

np.random.seed(29)

In [2]:
### set number of trials

n_trials = 10_000
n_rows = 10_000

##roll three dice

n_dice = 3
n_col = 3

#use np random choice
# to select from [1,2,3,4,5,6]

rolls = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(n_rows, n_col)

rolls

array([[6, 4, 5],
       [6, 3, 1],
       [1, 2, 2],
       ...,
       [6, 2, 1],
       [3, 4, 3],
       [4, 2, 4]])

In [3]:
sum_by_trials = rolls.sum(axis=1)

In [5]:
viz.simulation_example(sum_by_trials)

AttributeError: module 'viz' has no attribute 'simulation_example'

In [7]:
help(viz)

Help on package viz:

NAME
    viz

PACKAGE CONTENTS
    cli
    format
    geom
    gloss
    stats
    terminal
    text

FILE
    /usr/local/anaconda3/lib/python3.9/site-packages/viz/__init__.py




In [6]:
help(viz)

Help on package viz:

NAME
    viz

PACKAGE CONTENTS
    cli
    format
    geom
    gloss
    stats
    terminal
    text

FILE
    /usr/local/anaconda3/lib/python3.9/site-packages/viz/__init__.py




In [7]:
viz

<module 'viz' from '/usr/local/anaconda3/lib/python3.9/site-packages/viz/__init__.py'>

In [8]:
p_nap = 0.3

ndays = ncols = 2

n_simulated_weekends = nrows = 10**5

In [9]:
data = np.random.random((nrows, ncols))

In [10]:
data

array([[0.46762045, 0.70078355],
       [0.18897809, 0.54312897],
       [0.253291  , 0.43836437],
       ...,
       [0.15008559, 0.37577491],
       [0.34690321, 0.58934311],
       [0.97135998, 0.57219933]])

In [13]:
naps = data < p_nap
naps

array([[False, False],
       [ True, False],
       [ True, False],
       ...,
       [ True, False],
       [False, False],
       [False, False]])

In [14]:
naps.sum(axis=1)

array([0, 1, 1, ..., 1, 0, 0])

In [16]:
((naps.sum(axis=1) >= 1) == 1).mean()

0.50998

In [17]:
((naps.sum(axis=1) >= 1) == 0).mean()

0.49002

In [19]:
n_simulations = nrows = 10**5
n_dice_rolled = ncols = 3

rolls = np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols)

(pd.DataFrame(rolls)
 .apply(lambda row: 3 in row.values, axis=1)
 .mean())


0.4212

In [24]:
(pd.DataFrame(rolls)
 .apply(lambda row: 3 in row, axis=1)
 .head())

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [22]:
(pd.DataFrame(rolls)
 .apply(lambda row: 3 in row.values, axis=1)
 .head())

0     True
1    False
2     True
3    False
4    False
dtype: bool